<?php

namespace App\Enums;

use App\Enums\Concerns\HasValues;

/**
 * Whether a service is generated by an in-house pipeline (internal) or
 * proxied to a third-party provider (external, via external_url).
 */
enum ServiceKind: string
{
    use HasValues;

    case Internal = 'internal';
    case External = 'external';
}
